### ISSUE TITLE
Write a base class of Inheritance, derived classes and method

### ISSUE THREAD

**Issue by memorisecodead** [zark1cerut/cxx#2]
## Description:
1. Create a variant base class with 2 or more fields and define a constructor, a destructor and a method for displaying the values of the class fields. 
2. You have to develop derived classes, in which you have to add at least 1 field and methods of your own (constructor, destructor, method for outputting class fields and method, which implements the variant task). 
3. Create objects of developed classes and check the operation of methods implemented in them.

**Comment by zark1cerut** [comment]
Add in branch dev my realization of Inheritance
